import { Card, Col, Divider, Dropdown, Flex, MenuProps, Row, Tag } from "antd";
import { useStyles } from "./MyCoursesCardsStyles";
import { Star, DotsThree, User } from "@assets";
import { Typography } from "antd";

const { Title, Text } = Typography;

export const MyCoursesCards = () => {
  const { styles } = useStyles();

  const data = [
    {
      id: 1,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.9,
      students: 982941,
      price: 24.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=1",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 2,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.0,
      students: 511123,
      price: 49.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=2",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 3,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 5.0,
      students: 197637,
      price: 23.0,
      oldPrice: 35.0,
      image: "https://source.unsplash.com/random/300x200?sig=3",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 4,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.3,
      students: 211434,
      price: 89.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=4",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 5,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.7,
      students: 702345,
      price: 69.0,
      oldPrice: 99.0,
      image: "https://source.unsplash.com/random/300x200?sig=5",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 6,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.6,
      students: 345678,
      price: 39.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=6",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 7,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.8,
      students: 621456,
      price: 79.0,
      oldPrice: 119.0,
      image: "https://source.unsplash.com/random/300x200?sig=7",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 8,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.5,
      students: 278901,
      price: 45.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=8",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 9,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.9,
      students: 312456,
      price: 59.0,
      oldPrice: 89.0,
      image: "https://source.unsplash.com/random/300x200?sig=9",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 10,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.4,
      students: 128973,
      price: 19.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=10",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 11,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.7,
      students: 765432,
      price: 27.0,
      oldPrice: 40.0,
      image: "https://source.unsplash.com/random/300x200?sig=11",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 12,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.6,
      students: 498123,
      price: 44.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=12",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 13,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 4.8,
      students: 234567,
      price: 29.0,
      oldPrice: 45.0,
      image: "https://source.unsplash.com/random/300x200?sig=13",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 14,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.2,
      students: 189234,
      price: 94.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=14",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 15,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.9,
      students: 654321,
      price: 64.0,
      oldPrice: 89.0,
      image: "https://source.unsplash.com/random/300x200?sig=15",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 16,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.3,
      students: 321456,
      price: 34.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=16",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 17,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.7,
      students: 543210,
      price: 84.0,
      oldPrice: 129.0,
      image: "https://source.unsplash.com/random/300x200?sig=17",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 18,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.6,
      students: 267890,
      price: 50.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=18",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 19,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.8,
      students: 298765,
      price: 54.0,
      oldPrice: 79.0,
      image: "https://source.unsplash.com/random/300x200?sig=19",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 20,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.5,
      students: 143210,
      price: 21.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=20",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 21,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.4,
      students: 876543,
      price: 30.0,
      oldPrice: 50.0,
      image: "https://source.unsplash.com/random/300x200?sig=21",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 22,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.9,
      students: 456789,
      price: 39.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=22",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 23,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 4.7,
      students: 210987,
      price: 25.0,
      oldPrice: 40.0,
      image: "https://source.unsplash.com/random/300x200?sig=23",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 24,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.1,
      students: 176543,
      price: 99.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=24",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 25,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.8,
      students: 598765,
      price: 59.0,
      oldPrice: 85.0,
      image: "https://source.unsplash.com/random/300x200?sig=25",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 26,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.4,
      students: 287654,
      price: 29.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=26",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 27,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.6,
      students: 432109,
      price: 89.0,
      oldPrice: 139.0,
      image: "https://source.unsplash.com/random/300x200?sig=27",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 28,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.3,
      students: 234567,
      price: 55.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=28",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 29,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.7,
      students: 276543,
      price: 49.0,
      oldPrice: 69.0,
      image: "https://source.unsplash.com/random/300x200?sig=29",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 30,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.2,
      students: 165432,
      price: 23.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=30",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 31,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.5,
      students: 987654,
      price: 33.0,
      oldPrice: 55.0,
      image: "https://source.unsplash.com/random/300x200?sig=31",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 32,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.8,
      students: 543210,
      price: 34.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=32",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 33,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 4.6,
      students: 187654,
      price: 27.0,
      oldPrice: 42.0,
      image: "https://source.unsplash.com/random/300x200?sig=33",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 34,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.0,
      students: 154321,
      price: 104.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=34",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 35,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.9,
      students: 543210,
      price: 54.0,
      oldPrice: 79.0,
      image: "https://source.unsplash.com/random/300x200?sig=35",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 36,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.1,
      students: 254321,
      price: 24.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=36",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 37,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.5,
      students: 321098,
      price: 94.0,
      oldPrice: 149.0,
      image: "https://source.unsplash.com/random/300x200?sig=37",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 38,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.4,
      students: 201234,
      price: 60.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=38",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 39,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.6,
      students: 254321,
      price: 44.0,
      oldPrice: 64.0,
      image: "https://source.unsplash.com/random/300x200?sig=39",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 40,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.3,
      students: 187654,
      price: 25.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=40",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 41,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.7,
      students: 876543,
      price: 36.0,
      oldPrice: 60.0,
      image: "https://source.unsplash.com/random/300x200?sig=41",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 42,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.2,
      students: 432109,
      price: 29.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=42",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 43,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 4.5,
      students: 165432,
      price: 30.0,
      oldPrice: 48.0,
      image: "https://source.unsplash.com/random/300x200?sig=43",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 44,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.8,
      students: 132109,
      price: 109.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=44",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 45,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.4,
      students: 487654,
      price: 49.0,
      oldPrice: 74.0,
      image: "https://source.unsplash.com/random/300x200?sig=45",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 46,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.9,
      students: 221098,
      price: 19.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=46",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 47,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.3,
      students: 298765,
      price: 99.0,
      oldPrice: 159.0,
      image: "https://source.unsplash.com/random/300x200?sig=47",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 48,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.1,
      students: 167890,
      price: 65.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=48",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 49,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.5,
      students: 232109,
      price: 39.0,
      oldPrice: 59.0,
      image: "https://source.unsplash.com/random/300x200?sig=49",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 50,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.2,
      students: 334566,
      price: 22.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=50",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 51,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.6,
      students: 765432,
      price: 39.0,
      oldPrice: 65.0,
      image: "https://source.unsplash.com/random/300x200?sig=51",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 52,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.7,
      students: 321098,
      price: 24.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=52",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 53,
      title: "Data Structures & Algorithms Essentials (2021)",
      category: "Developments",
      rating: 4.4,
      students: 143210,
      price: 33.0,
      oldPrice: 50.0,
      image: "https://source.unsplash.com/random/300x200?sig=53",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 54,
      title: "Data Science A-Z™: Hands-On Exercises",
      category: "Developments",
      rating: 4.9,
      students: 109876,
      price: 114.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=54",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 55,
      title: "React - The Complete Guide (incl Hooks, Redux)",
      category: "Developments",
      rating: 4.3,
      students: 432109,
      price: 44.0,
      oldPrice: 69.0,
      image: "https://source.unsplash.com/random/300x200?sig=55",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 56,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.8,
      students: 187654,
      price: 14.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=56",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 57,
      title: "Machine Learning A-Z: Hands-On Python & R",
      category: "Developments",
      rating: 4.2,
      students: 276543,
      price: 104.0,
      oldPrice: 169.0,
      image: "https://source.unsplash.com/random/300x200?sig=57",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 58,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.0,
      students: 134567,
      price: 70.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=58",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 59,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.4,
      students: 210987,
      price: 34.0,
      oldPrice: 54.0,
      image: "https://source.unsplash.com/random/300x200?sig=59",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 60,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.1,
      students: 298765,
      price: 20.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=60",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 61,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.5,
      students: 654321,
      price: 45.0,
      oldPrice: 70.0,
      image: "https://source.unsplash.com/random/300x200?sig=61",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 62,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.6,
      students: 209876,
      price: 19.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=62",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 63,
      title: "Data Structures & Algorithms Essentials",
      category: "Developments",
      rating: 4.3,
      students: 121121,
      price: 36.99,
      oldPrice: 55.0,
      image: "https://source.unsplash.com/random/300x200?sig=63",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 64,
      title: "Data Science A-Z™: Hands-On™",
      category: "Developments",
      rating: 4.8,
      students: 87654,
      price: 119.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=64",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 65,
      title: "React - The Complete Guide",
      category: "Developments",
      rating: 4.2,
      students: 376543,
      price: 49.99,
      oldPrice: 74.99,
      image: "https://source.unsplash.com/random/300x200?sig=65",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 66,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.7,
      students: 154432,
      price: 24.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=66",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 67,
      title: "Machine Learning A-Z™: Hands-On Python & R",
      category: "Developments",
      rating: 4.1,
      students: 254432,
      price: 109.99,
      oldPrice: 179.99,
      image: "https://source.unsplash.com/random/300x200?sig=67",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 68,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.9,
      students: 101234,
      price: 64.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=68",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 69,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.0,
      students: 189123,
      price: 44.99,
      oldPrice: 64.99,
      image: "https://source.unsplash.com/random/300x200?sig=69",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 70,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.4,
      students: 276432,
      price: 21.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=70",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 71,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.8,
      students: 543210,
      price: 39.99,
      oldPrice: 65.0,
      image: "https://source.unsplash.com/random/300x200?sig=71",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 72,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.0,
      students: 187654,
      price: 24.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=72",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 73,
      title: "Data Structures & Algorithms Essentials",
      category: "Developments",
      rating: 4.6,
      students: 132432,
      price: 38.99,
      oldPrice: 60.0,
      image: "https://source.unsplash.com/random/300x200?sig=73",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 74,
      title: "Data Science A-Z™: Hands-On",
      category: "Developments",
      rating: 4.7,
      students: 65432,
      price: 124.0,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=74",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 75,
      title: "React - The Complete Guide",
      category: "Developments",
      rating: 4.1,
      students: 321098,
      price: 54.99,
      oldPrice: 84.99,
      image: "https://source.unsplash.com/random/300x200?sig=75",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 76,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.5,
      students: 121432,
      price: 34.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=76",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 77,
      title: "Machine Learning A-Z™: Hands-On Python & R",
      category: "Developments",
      rating: 4.2,
      students: 234432,
      price: 114.99,
      oldPrice: 189.99,
      image: "https://source.unsplash.com/random/300x200?sig=77",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 78,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.3,
      students: 87654,
      price: 69.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=78",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 79,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.8,
      students: 167890,
      price: 49.99,
      oldPrice: 70.0,
      image: "https://source.unsplash.com/random/300x200?sig=79",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 80,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.9,
      students: 254432,
      price: 22.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=80",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 81,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.4,
      students: 432109,
      price: 39.99,
      oldPrice: 75.0,
      image: "https://source.unsplash.com/random/300x200?sig=81",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 82,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.5,
      students: 98765,
      price: 29.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=82",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 83,
      title: "Data Structures & Algorithms Essentials",
      category: "Developments",
      rating: 4.0,
      students: 143210,
      price: 39.99,
      oldPrice: 65.0,
      image: "https://source.unsplash.com/random/300x200?sig=83",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 84,
      title: "Data Science A-Z™: Hands-On",
      category: "Developments",
      rating: 4.6,
      students: 109876,
      price: 99.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=84",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 85,
      title: "React - The Complete Guide",
      category: "Developments",
      rating: 4.7,
      students: 432432,
      price: 59.99,
      oldPrice: 89.99,
      image: "https://source.unsplash.com/random/300x200?sig=85",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 86,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.2,
      students: 87654,
      price: 44.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=86",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 87,
      title: "Machine Learning A-Z™: Hands-On Python & R",
      category: "Developments",
      rating: 4.8,
      students: 210987,
      price: 119.99,
      oldPrice: 199.99,
      image: "https://source.unsplash.com/random/300x200?sig=87",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 88,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.9,
      students: 65432,
      price: 34.49,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=88",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 89,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.1,
      students: 143210,
      price: 54.99,
      oldPrice: 79.99,
      image: "https://source.unsplash.com/random/300x200?sig=89",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 90,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.5,
      students: 234567,
      price: 24.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=90",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 91,
      title: "Premiere Pro CC for Beginners: Video Editing in Premiere",
      category: "Developments",
      rating: 4.6,
      students: 321456,
      price: 49.99,
      oldPrice: 80.0,
      image: "https://source.unsplash.com/random/300x200?sig=91",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 92,
      title: "Learn Python Programming Masterclass",
      category: "Developments",
      rating: 4.8,
      students: 98765,
      price: 34.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=92",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 93,
      title: "Data Structures & Algorithms Essentials",
      category: "Developments",
      rating: 4.2,
      students: 167890,
      price: 39.99,
      oldPrice: 70.0,
      image: "https://source.unsplash.com/random/300x200?sig=93",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 94,
      title: "Data Science A-Z™: Hands-On",
      category: "Developments",
      rating: 4.0,
      students: 87654,
      price: 104.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=94",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 95,
      title: "React - The Complete Guide",
      category: "Developments",
      rating: 4.7,
      students: 543210,
      price: 64.99,
      oldPrice: 94.99,
      image: "https://source.unsplash.com/random/300x200?sig=95",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 96,
      title: "Modern JavaScript From The Beginning",
      category: "Developments",
      rating: 4.3,
      students: 65432,
      price: 29.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=96",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 97,
      title: "Machine Learning A-Z™: Hands-On Python & R",
      category: "Developments",
      rating: 4.9,
      students: 189123,
      price: 124.99,
      oldPrice: 209.99,
      image: "https://source.unsplash.com/random/300x200?sig=97",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 98,
      title: "Web Design for Beginners: Real World Coding",
      category: "Developments",
      rating: 4.4,
      students: 43210,
      price: 39.49,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=98",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 99,
      title: "Docker & Kubernetes: The Complete Guide",
      category: "Developments",
      rating: 4.6,
      students: 121098,
      price: 59.99,
      oldPrice: 84.99,
      image: "https://source.unsplash.com/random/300x200?sig=99",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
    {
      id: 100,
      title: "HTML, CSS, and JS for Web Developers",
      category: "Developments",
      rating: 4.8,
      students: 210987,
      price: 29.99,
      oldPrice: null,
      image: "https://source.unsplash.com/random/300x200?sig=100",
      link: "https://media.2x2tv.ru/content/images/2021/04/spor.jpg",
    },
  ];

  const items: MenuProps["items"] = [
    {
      key: "1",
      label: "My Account",
    },
    {
      type: "divider",
    },
    {
      key: "2",
      label: "Profile",
    },
    {
      key: "3",
      label: "Billing",
    },
    {
      key: "4",
      label: "Settings",
    },
  ];

  return (
    <Flex vertical className={styles.container}>
      <Row gutter={[24, 24]}>
        {data.map((item) => (
          <Col key={item.id} className="gutter-row" md={12} lg={8} xl={6}>
            <Card hoverable cover={<img alt="example" src={item.link} />}>
              <Flex vertical>
                <Tag color="geekblue" className={styles.tag}>
                  {item.category}
                </Tag>
                <Title level={5}>{item.title}</Title>
                <Divider className={styles.divider} />
                <Flex justify="space-between" align="center" gap={24}>
                  <Flex align="center" gap={6}>
                    <Star />
                    <Text className={styles.text}>{item.rating}</Text>
                  </Flex>
                  <Flex align="center" gap={6}>
                    <User />
                    {item.students}
                    <Text type="secondary" color="#4E5566">
                      {" "}
                      students
                    </Text>
                  </Flex>
                </Flex>
                <Divider className={styles.divider} />
                <Flex justify="space-between" align="center">
                  <div className={styles.price}>${item.price}</div>
                  <Dropdown menu={{ items }} trigger={["hover"]} arrow>
                    <div tabIndex={0}>
                      <DotsThree />
                    </div>
                  </Dropdown>
                </Flex>
              </Flex>
            </Card>
          </Col>
        ))}
      </Row>
    </Flex>
  );
};
